### ISSUE TITLE
Import custom theme statuses

### ISSUE THREAD

**Issue by bhemmelgarn** [vburzynski/obsidian-task-status#1]
**Is your feature request related to a problem? Please describe.**
It would be great to import the list of statuses available through custom themes. 

**Describe the solution you'd like**
[Tasks does this](https://publish.obsidian.md/tasks/Getting+Started/Statuses/Custom+Statuses#Setting+up+your+custom+statuses), and it works very well

**Additional context**
This is a great little plugin! Love what it does already. This would just be a nice QoL addition.

**Comment by vburzynski** [comment]
Thanks for the feature request 😎 I've thought that this would be useful as well and postponed it for after the initial release. It's on the roadmap.
