### ISSUE TITLE
Indentation is partially not preserved with cursor placement

### ISSUE THREAD

**Issue by stef-rausch** [vburzynski/obsidian-task-status#2]
**Describe the bug**

Placing the cursor, i.e., not (partially) selecting a line, and applying a new task status does not preserve the original indentation, which is removed. The bug comes up with indented plain lines and bullet (non-task) lines.

**To Reproduce**

1. Write a new note with the following content:

```
test
    test 1

- test
    - test 2
```

2. Place the cursor on the line of either `test 1` or `test 2`.
3. Apply a task status change.
4. The indentation is removed.

**Expected behavior**

The original indentation level should be preserved.

**Desktop (please complete the following information):**

 - OS: Windows 11

**Additional context**

- Obsidian (installer) version: 1.5.3.
- Theme: Minimal version 7.4.7.

**Comment by vburzynski** [comment]
@StefanoRausch I believe I've fixed the issue you were describing and will include it in the next release 🙂 it's merged into the main branch for now.
