### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by albertoloscerritos** [vburzynski/obsidian-task-status#5]
Hi, thanks for the awesome job. 
One question, do you happen to know why I am not seen the icons of the checkboxes when I want to select them (see the following gif)...
![checkbox](https://github.com/user-attachments/assets/753a7f1c-b48c-4620-b7c6-c430f31cbab7)
I am using the ITS theme css snippet checkboxes and obsidian 1.7.3
Thanks :)

**Comment by albertoloscerritos** [comment]
Btw I am using the AnuPpuccin theme (with AnuPpuccin custom checkboxes disabled), but the checkboxes from the ITS theme via css snippet, in case that's relevant. Thanks

**Comment by garbosz** [comment]
im seeing a similar issue but only partially, most core checkboxes work but im notably missing the GIT checkbox designs and all of the checkboxes provided by the integrated themes

**Comment by vburzynski** [comment]
Just seeing this 🤔 
In my personal setup I have AnuPpuccin along with some of my own custom CSS; I'll test some things this weekend in a new blank vault.  It's possible I have a custom modification in my CSS styles. Doh.

**Comment by vburzynski** [comment]
I think I found the issue and I'm working on a fix. The CSS Selectors used by the ITS Theme for checkboxes are more particular than some of the other themes and the selectors also have a higher specificity. I'll need to change a few things about the HTML I'm constructing for the Suggestion Modal.

**Comment by albertoloscerritos** [comment]
Thanks for the help and the awesome plugin.
