### ISSUE TITLE
"Failed to install plugin" on 1.2.1

### ISSUE THREAD

**Issue by Glint-Eye** [vburzynski/obsidian-task-status#7]
Downloading most current version 1.2.1 of Task Status from community plugins under Linux .deb version of Obsidian 1.7.4 throws a "Failed to install plugin" notification and doesnt' install plugin.

**Comment by vburzynski** [comment]
huh... I saw that I forgot to finish pushing up a GitHub release of 1.2.1 and just pushed that; Odd thing is that everything installed fine from the community plugins when I tested on my mac. Not sure why that would be different, that's interesting... 🤔

Can you try installing again? 
_Or if it fails again, are there any additional details in the console of the developer tools? What version of Linux?_

**Comment by Glint-Eye** [comment]
install was successful. thx a lot :)
